language: generic
services:
    - docker

before_install:
    - docker build -t kishorenewton/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true kishorenewton/react-test npm test 

after_success:
    - docker build -t kishorenewton/multi-client ./client
    - docker build -t kishorenewton/multi-nginx ./nginx
    - docker build -t kishorenewton/multi-server ./server
    - docker build -t kishorenewton/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push kishorenewton/multi-client 
    - docker push kishorenewton/multi-nginx
    - docker push kishorenewton/multi-server
    - docker push kishorenewton/multi-worker

deploy: 
    provide: elasticbeanstalk
    region: us-east-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-1-101114061564
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY